mp_core.o: mp_core.c config.h mp.h
mpv_ansi.o: mpv_ansi.c config.h mp.h
mpv_curses.o: mpv_curses.c config.h mp.h
mpv_gtk.o: mpv_gtk.c config.h mp.h
mpv_win32.o: mpv_win32.c config.h mp.h
mpv_win32c.o: mpv_win32c.c config.h mp.h
